/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sewapc;
import javax.swing.JFrame;
import javax.swing.JOptionPane;




/**
 *
 * @author Windows 8.1
 */
public class home extends javax.swing.JFrame {

    public home() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false); 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        btnKomputer = new javax.swing.JButton();
        btnPelanggan = new javax.swing.JButton();
        btnSewa = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        transaksi1 = new javax.swing.JButton();
        desktopPaneControl = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 660));
        setSize(new java.awt.Dimension(1000, 660));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        menu.setBackground(new java.awt.Color(0, 102, 153));
        menu.setMaximumSize(new java.awt.Dimension(210, 660));
        menu.setMinimumSize(new java.awt.Dimension(210, 660));

        btnKomputer.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        btnKomputer.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnKomputer.setForeground(new java.awt.Color(0, 102, 153));
        btnKomputer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pc.png"))); // NOI18N
        btnKomputer.setText("KOMPUTER");
        btnKomputer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKomputer.setIconTextGap(10);
        btnKomputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKomputerActionPerformed(evt);
            }
        });

        btnPelanggan.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        btnPelanggan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnPelanggan.setForeground(new java.awt.Color(0, 102, 153));
        btnPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/human-queue256x256.png"))); // NOI18N
        btnPelanggan.setText("PELANGGAN");
        btnPelanggan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPelanggan.setIconTextGap(10);
        btnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelangganActionPerformed(evt);
            }
        });

        btnSewa.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        btnSewa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSewa.setForeground(new java.awt.Color(0, 102, 153));
        btnSewa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pay.png"))); // NOI18N
        btnSewa.setText("SEWA");
        btnSewa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSewa.setIconTextGap(10);
        btnSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSewaActionPerformed(evt);
            }
        });

        keluar.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        keluar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        keluar.setForeground(new java.awt.Color(153, 0, 0));
        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/alternate-sign-out256x195.png"))); // NOI18N
        keluar.setText("Log Out");
        keluar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        keluar.setIconTextGap(10);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/3.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        transaksi1.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        transaksi1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        transaksi1.setForeground(new java.awt.Color(0, 102, 153));
        transaksi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-help-about-icon (1).png"))); // NOI18N
        transaksi1.setText("TENTANG");
        transaksi1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        transaksi1.setIconTextGap(10);
        transaksi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksi1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(transaksi1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                        .addGap(23, 23, 23))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnKomputer, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 22, Short.MAX_VALUE))))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnKomputer, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(transaksi1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        desktopPaneControl.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));

        javax.swing.GroupLayout desktopPaneControlLayout = new javax.swing.GroupLayout(desktopPaneControl);
        desktopPaneControl.setLayout(desktopPaneControlLayout);
        desktopPaneControlLayout.setHorizontalGroup(
            desktopPaneControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
        );
        desktopPaneControlLayout.setVerticalGroup(
            desktopPaneControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPaneControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(desktopPaneControl)
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void transaksi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksi1ActionPerformed
        // TODO add your handling code here:
        desktopPaneControl.removeAll();
        profile f4=new profile();
        desktopPaneControl.add(f4).setVisible(true);
    }//GEN-LAST:event_transaksi1ActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Yakin mau keluar?\nPas balik harus masuk akun lagi", "Select", JOptionPane.YES_NO_OPTION);
        if (a==0)
        {
        login Flogin = new login();
        Flogin.setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void btnSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSewaActionPerformed
        // TODO add your handling code here:
        desktopPaneControl.removeAll();
        transaksi f3=new transaksi();
        desktopPaneControl.add(f3).setVisible(true);
    }//GEN-LAST:event_btnSewaActionPerformed

    private void btnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelangganActionPerformed
        // TODO add your handling code here:
        desktopPaneControl.removeAll();
        pelanggan f2=new pelanggan();
        desktopPaneControl.add(f2).setVisible(true);
    }//GEN-LAST:event_btnPelangganActionPerformed

    private void btnKomputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKomputerActionPerformed
        // TODO add your handling code here:
        desktopPaneControl.removeAll();
        komputer f1=new komputer();
        desktopPaneControl.add(f1).setVisible(true);
    }//GEN-LAST:event_btnKomputerActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
     
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main (String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKomputer;
    private javax.swing.JButton btnPelanggan;
    private javax.swing.JButton btnSewa;
    private javax.swing.JDesktopPane desktopPaneControl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton keluar;
    private javax.swing.JPanel menu;
    private javax.swing.JButton transaksi1;
    // End of variables declaration//GEN-END:variables
}
